baseURL = "http://blog.rxbc.se"
languageCode = "en-GB"
title = "Viktor's blog"

theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

titleCaseStyle = "firstupper"

[params]
env = "production"
description = "Viktor's blog"
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowFullTextinRSS = true
ShowCodeCopyButtons = true
mainSections = ["posts"]

[params.assets]
disableHLJS = true

[menu]
main = [
  { identifier = "posts", name = "posts", url = "/posts/", weight = 10 },
  { identifier = "about", name = "about", url = "/about/", weight = 20 },
]

[markup]
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  lineNos = true
  noClasses = true
  style = 'monokai'
  tabWidth = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[module]
  [[module.imports]]
    path = "github.com/martignoni/hugo-notice"
  [[module.imports]]
    path = "PaperMod"
